import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "@/styles/index.css";
import Topbar from "@/components/layout/Topbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const mono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist",
  weight: ["100", "200", "300", "400", "500", "600", "700", "900", "800"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${mono.variable} antialiased overflow-hidden flex flex-col`}
      >
        <Topbar />
        {/* <div className="absolute bg-green-500 size-[400px] opacity-30 rounded-full blur-[200px] " ></div> */}
        <div className="w-[calc(100%-64px)] bg-white z-[9999999] ml-[64px] mx-auto border-l-2 border-t-2 rounded-corners rounded-r-none rounded-b-none h-[calc(100dvh-56px)] overflow-x-hidden overflow-y-auto border-black/15" >
        {children}
        </div>
      </body>
    </html>
  );
}
